//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1109_MemberClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/_1109_MemberService")]
    [System.SerializableAttribute()]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GName {
            get {
                return this.GNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GNameField, value) != true)) {
                    this.GNameField = value;
                    this.RaisePropertyChanged("GName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GNumber {
            get {
                return this.GNumberField;
            }
            set {
                if ((this.GNumberField.Equals(value) != true)) {
                    this.GNumberField = value;
                    this.RaisePropertyChanged("GNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MNumber {
            get {
                return this.MNumberField;
            }
            set {
                if ((this.MNumberField.Equals(value) != true)) {
                    this.MNumberField = value;
                    this.RaisePropertyChanged("MNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPhone {
            get {
                return this.MPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MPhoneField, value) != true)) {
                    this.MPhoneField = value;
                    this.RaisePropertyChanged("MPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMemberService")]
    public interface IMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Insert", ReplyAction="http://tempuri.org/IMemberService/InsertResponse")]
        bool Insert(string name, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Insert", ReplyAction="http://tempuri.org/IMemberService/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(string name, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Delete", ReplyAction="http://tempuri.org/IMemberService/DeleteResponse")]
        bool Delete(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Delete", ReplyAction="http://tempuri.org/IMemberService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/update", ReplyAction="http://tempuri.org/IMemberService/updateResponse")]
        bool update(int gnumber, int mnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/update", ReplyAction="http://tempuri.org/IMemberService/updateResponse")]
        System.Threading.Tasks.Task<bool> updateAsync(int gnumber, int mnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/SelectAll_Table", ReplyAction="http://tempuri.org/IMemberService/SelectAll_TableResponse")]
        System.Data.DataTable SelectAll_Table();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/SelectAll_Table", ReplyAction="http://tempuri.org/IMemberService/SelectAll_TableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SelectAll_TableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Select_Number", ReplyAction="http://tempuri.org/IMemberService/Select_NumberResponse")]
        _1109_MemberClient.ServiceReference1.Member Select_Number(int mnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Select_Number", ReplyAction="http://tempuri.org/IMemberService/Select_NumberResponse")]
        System.Threading.Tasks.Task<_1109_MemberClient.ServiceReference1.Member> Select_NumberAsync(int mnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Select_Group", ReplyAction="http://tempuri.org/IMemberService/Select_GroupResponse")]
        System.Data.DataTable Select_Group(int gnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemberService/Select_Group", ReplyAction="http://tempuri.org/IMemberService/Select_GroupResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Select_GroupAsync(int gnumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberServiceChannel : _1109_MemberClient.ServiceReference1.IMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServiceClient : System.ServiceModel.ClientBase<_1109_MemberClient.ServiceReference1.IMemberService>, _1109_MemberClient.ServiceReference1.IMemberService {
        
        public MemberServiceClient() {
        }
        
        public MemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Insert(string name, string phone) {
            return base.Channel.Insert(name, phone);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(string name, string phone) {
            return base.Channel.InsertAsync(name, phone);
        }
        
        public bool Delete(int number) {
            return base.Channel.Delete(number);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int number) {
            return base.Channel.DeleteAsync(number);
        }
        
        public bool update(int gnumber, int mnumber) {
            return base.Channel.update(gnumber, mnumber);
        }
        
        public System.Threading.Tasks.Task<bool> updateAsync(int gnumber, int mnumber) {
            return base.Channel.updateAsync(gnumber, mnumber);
        }
        
        public System.Data.DataTable SelectAll_Table() {
            return base.Channel.SelectAll_Table();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SelectAll_TableAsync() {
            return base.Channel.SelectAll_TableAsync();
        }
        
        public _1109_MemberClient.ServiceReference1.Member Select_Number(int mnumber) {
            return base.Channel.Select_Number(mnumber);
        }
        
        public System.Threading.Tasks.Task<_1109_MemberClient.ServiceReference1.Member> Select_NumberAsync(int mnumber) {
            return base.Channel.Select_NumberAsync(mnumber);
        }
        
        public System.Data.DataTable Select_Group(int gnumber) {
            return base.Channel.Select_Group(gnumber);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Select_GroupAsync(int gnumber) {
            return base.Channel.Select_GroupAsync(gnumber);
        }
    }
}
